export const dummydata = [
    {
      id: 1,
      user: "Alice",
      game: "Slot Machine",
      betAmount: "0.005 BTC",
      add: true,
      payout: "+0.015 BTC",
    },
    {
      id: 2,
      user: "Bob",
      game: "Roulette",
      betAmount: "0.01 ETH",
      add: true,
      payout: "+0.03 ETH",
    },
    {
      id: 3,
      user: "Charlie",
      game: "Blackjack",
      betAmount: "0.02 BTC",
      add: true,
      payout: "+0.04 BTC",
    },
    {
      id: 4,
      user: "David",
      game: "Dice",
      betAmount: "0.5 BTC",
      add: false,
      payout: "-1.0 BTC",
    },
    {
      id: 5,
      user: "Eve",
      game: "Poker",
      betAmount: "0.9 ETH",
      add: false,
      payout: "-200 ETH",
    },
    {
      id: 6,
      user: "Frank",
      game: "Baccarat",
      betAmount: "10 BTC",
      add: false,
      payout: "-20 BTC",
    },
    {
        id: 7,
        user: "Grace",
        game: "Craps",
        betAmount: "50 BTC",
        add: true,
        payout: "+0.9 BTC",
    },
    {
        id: 8,
        user: "Harry",
        game: "Keno",
        betAmount: "200 ETH",
        add: true,
        payout: "+400 ETH",
    },
    {
        id: 9,
        user: "Ivy",
        game: "Sic Bo",
        betAmount: "0.1 BTC",
        add: false,
        payout: "-0.2 BTC",
    },
    {
        id: 10,
        user: "Jack",
        game: "Wheel of Fortune",
        betAmount: "1 ETH",
        add: true,
        payout: "+2 ETH",
    },
    {
        id: 11,
        user: "Kate",
        game: "Bingo",
        betAmount: "5 BTC",
        add: true,
        payout: "+10 BTC",
    },
    {
        id: 12,
        user: "Liam",
        game: "Hi-Lo",
        betAmount: "0.01 ETH",
        add: true,
        payout: "+0.02 ETH",
    },
    {
        id: 13,
        user: "Mia",
        game: "Pai Gow Poker",
        betAmount: "0.05 BTC",
        add: true,
        payout: "+0.1 BTC",
    },
    {
        id: 14,
        user: "Noah",
        game: "Texas Hold'em",
        betAmount: "0.1 ETH",
        add: true,
        payout: "+0.2 ETH",
    },
    {
        id: 15,
        user: "Olivia",
        game: "Bingo",
        betAmount: "0.5 BTC",
        add: false,
        payout: "-1.0 BTC",
    },
    {
        id: 16,
        user: "Peter",
        game: "Keno",
        betAmount: "0.90 ETH",
        add: false,
        payout: "-2000 ETH",
    },
    {
        id: 17,
        user: "Quinn",
        game: "Craps",
        betAmount: "5 BTC",
        add: false,
        payout: "-10 BTC",
    },
    {
        id: 18,
        user: "Rachel",
        game: "Poker",
        betAmount: "0.05 ETH",
        add: false,
        payout: "-0.1 ETH",
    },
    {
        id: 19,
        user: "Sam",
        game: "Blackjack",
        betAmount: "10 BTC",
        add: false,
        payout: "-20 BTC",
    },
    {
        id: 20,
        user: "Tom",
        game: "Slot Machine",
        betAmount: "0.005 ETH",
        add: false,
        payout: "-0.015 ETH",
    },
    {
        id: 21,
        user: "Uma",
        game: "Roulette",
        betAmount: "0.01 BTC",
        add: false,
        payout: "-0.03 BTC",
    },
    {
        id: 22,
        user: "Victor",
        game: "Dice",
        betAmount: "0.5 ETH",
        add: false,
        payout: "-1.0 ETH",
    },
    {
        id: 23,
        user: "Wendy",
        game: "Baccarat",
        betAmount: "10 BTC",
        add: false,
        payout: "-20 BTC",
    },
    {
        id: 24,
        user: "Xander",
        game: "Poker",
        betAmount: "0.90 ETH",
        add: false,
        payout: "-2000 ETH",
    },
    {
        id: 25,
        user: "Yara",
        game: "Blackjack",
        betAmount: "0.1 BTC",
        add: false,
        payout: "-0.2 BTC",
    },
    {
        id: 26,
        user: "Zoe",
        game: "Roulette",
        betAmount: "1 ETH",
        add: true,
        payout: "+2 ETH",
    },
    {
        id: 27,
        user: "Adam",
        game: "Slot Machine",
        betAmount: "0.01 BTC",
        add: true,
        payout: "+0.03 BTC",
    },
    {
        id: 28,
        user: "Becky",
        game: "Dice",
        betAmount: "0.05 ETH",
        add: true,
        payout: "+0.1 ETH",
    },
    {
        id: 29,
        user: "Carl",
        game: "Baccarat",
        betAmount: "0.90 BTC",
        add: true,
        payout: "+2000 BTC",
    },
    {
        id: 30,
        user: "Diana",
        game: "Poker",
        betAmount: "0.1 ETH",
        add: true,
        payout: "+0.2 ETH",
    },
    {
        id: 31,
        user: "Eric",
        game: "Craps",
        betAmount: "0.05 BTC",
        add: false,
        payout: "-0.1 BTC",
    },
    {
        id: 32,
        user: "Fiona",
        game: "Slot Machine",
        betAmount: "0.001 ETH",
        add: false,
        payout: "-0.003 ETH",
    },
    {
        id: 33,
        user: "George",
        game: "Roulette",
        betAmount: "0.5 BTC",
        add: false,
        payout: "-1.0 BTC",
    },
    {
        id: 34,
        user: "Holly",
        game: "Blackjack",
        betAmount: "10 ETH",
        add: false,
        payout: "-20 ETH",
    },
    {
        id: 35,
        user: "Ian",
        game: "Dice",
        betAmount: "0.01 BTC",
        add: false,
        payout: "-0.03 BTC",
    },
    {
        id: 36,
        user: "Julia",
        game: "Poker",
        betAmount: "0.05 ETH",
        add: false,
        payout: "-0.1 ETH",
    },
    {
        id: 37,
        user: "Kevin",
        game: "Slot Machine",
        betAmount: "0.1 BTC",
        add: false,
        payout: "-0.3 BTC",
    },
    {
        id: 38,
        user: "Lena",
        game: "Baccarat",
        betAmount: "0.5 ETH",
        add: false,
        payout: "-1.0 ETH",
    },
    {
        id: 39,
        user: "Mark",
        game: "Craps",
        betAmount: "0.05 BTC",
        add: false,
        payout: "-0.1 BTC",
    },
    {
        id: 40,
        user: "Nora",
        game: "Roulette",
        betAmount: "0.01 ETH",
        add: false,
        payout: "-0.03 ETH",
    },
    {
        id: 41,
        user: "Oscar",
        game: "Blackjack",
        betAmount: "0.1 BTC",
        add: false,
        payout: "-0.2 BTC",
    },
    {
        id: 42,
        user: "Paula",
        game: "Dice",
        betAmount: "0.05 ETH",
        add: false,
        payout: "-0.1 ETH",
    },
    {
        id: 43,
        user: "Quincy",
        game: "Poker",
        betAmount: "0.1 BTC",
        add: false,
        payout: "-0.3 BTC",
    },
    // Add more data...
    
  ];
  