export const dummydata = [
    {
      id: 1,
      user: "Alice",
      game: "Slot Machine",
      betAmount: "0.005 BTC",
      payout: "+0.015 BTC",
    },
    {
      id: 2,
      user: "Bob",
      game: "Roulette",
      betAmount: "0.01 ETH",
      payout: "+0.03 ETH",
    },
    {
      id: 3,
      user: "Charlie",
      game: "Blackjack",
      betAmount: "0.02 LTC",
      payout: "+0.04 LTC",
    },
    {
      id: 4,
      user: "David",
      game: "Dice",
      betAmount: "0.5 XRP",
      payout: "-1.0 XRP",
    },
    {
      id: 5,
      user: "Eve",
      game: "Poker",
      betAmount: "100 TRX",
      payout: "-200 TRX",
    },
    {
      id: 6,
      user: "Frank",
      game: "Baccarat",
      betAmount: "10 ADA",
      payout: "-20 ADA",
    },
    {
      id: 7,
      user: "Grace",
      game: "Craps",
      betAmount: "50 DOT",
      payout: "+100 DOT",
    },
    {
      id: 8,
      user: "Harry",
      game: "Keno",
      betAmount: "200 LINK",
      payout: "+400 LINK",
    },
    {
      id: 9,
      user: "Ivy",
      game: "Sic Bo",
      betAmount: "0.1 DOGE",
      payout: "-0.2 DOGE",
    },
    {
      id: 10,
      user: "Jack",
      game: "Wheel of Fortune",
      betAmount: "1 WAVES",
      payout: "+2 WAVES",
    },
    {
        id: 11,
        user: "Kate",
        game: "Bingo",
        betAmount: "5 BNB",
        payout: "+10 BNB",
      },
      {
        id: 12,
        user: "Liam",
        game: "Hi-Lo",
        betAmount: "0.01 ZEC",
        payout: "+0.02 ZEC",
      },
      {
        id: 13,
        user: "Mia",
        game: "Pai Gow Poker",
        betAmount: "0.05 ATOM",
        payout: "+0.1 ATOM",
      },
      {
        id: 14,
        user: "Noah",
        game: "Texas Hold'em",
        betAmount: "0.1 NEO",
        payout: "+0.2 NEO",
      },
      {
        id: 15,
        user: "Olivia",
        game: "Bingo",
        betAmount: "0.5 ALGO",
        payout: "-1.0 ALGO",
      },
      {
        id: 16,
        user: "Peter",
        game: "Keno",
        betAmount: "1000 USDT",
        payout: "-2000 USDT",
      },
      {
        id: 17,
        user: "Quinn",
        game: "Craps",
        betAmount: "5 LUNA",
        payout: "-10 LUNA",
      },
      {
        id: 18,
        user: "Rachel",
        game: "Poker",
        betAmount: "0.05 DASH",
        payout: "-0.1 DASH",
      },
      {
        id: 19,
        user: "Sam",
        game: "Blackjack",
        betAmount: "10 XLM",
        payout: "-20 XLM",
      },
      {
        id: 20,
        user: "Tom",
        game: "Slot Machine",
        betAmount: "0.005 ADA",
        payout: "-0.015 ADA",
      },
      {
        id: 21,
        user: "Uma",
        game: "Roulette",
        betAmount: "0.01 XTZ",
        payout: "-0.03 XTZ",
      },
      {
        id: 22,
        user: "Victor",
        game: "Dice",
        betAmount: "0.5 BUSD",
        payout: "-1.0 BUSD",
      },
      {
        id: 23,
        user: "Wendy",
        game: "Baccarat",
        betAmount: "10 EOS",
        payout: "-20 EOS",
      },
      {
        id: 24,
        user: "Xander",
        game: "Poker",
        betAmount: "1000 TRX",
        payout: "-2000 TRX",
      },
      {
        id: 25,
        user: "Yara",
        game: "Blackjack",
        betAmount: "0.1 BNB",
        payout: "-0.2 BNB",
      },
      {
        id: 26,
        user: "Zoe",
        game: "Roulette",
        betAmount: "1 WAVES",
        payout: "+2 WAVES",
      },
      {
        id: 27,
        user: "Adam",
        game: "Slot Machine",
        betAmount: "0.01 LTC",
        payout: "+0.03 LTC",
      },
      {
        id: 28,
        user: "Becky",
        game: "Dice",
        betAmount: "0.05 XRP",
        payout: "+0.1 XRP",
      },
      {
        id: 29,
        user: "Carl",
        game: "Baccarat",
        betAmount: "1000 TRX",
        payout: "+2000 TRX",
      },
      {
        id: 30,
        user: "Diana",
        game: "Poker",
        betAmount: "0.1 ETH",
        payout: "+0.2 ETH",
      },
      {
        id: 31,
        user: "Eric",
        game: "Craps",
        betAmount: "0.05 LTC",
        payout: "-0.1 LTC",
      },
      {
        id: 32,
        user: "Fiona",
        game: "Slot Machine",
        betAmount: "0.001 BTC",
        payout: "-0.003 BTC",
      },
      {
        id: 33,
        user: "George",
        game: "Roulette",
        betAmount: "0.5 ETH",
        payout: "-1.0 ETH",
      },
      {
        id: 34,
        user: "Holly",
        game: "Blackjack",
        betAmount: "10 TRX",
        payout: "-20 TRX",
      },
      {
        id: 35,
        user: "Ian",
        game: "Dice",
        betAmount: "0.01 ETH",
        payout: "-0.03 ETH",
      },
      {
        id: 36,
        user: "Julia",
        game: "Poker",
        betAmount: "0.05 LTC",
        payout: "-0.1 LTC",
      },
      {
        id: 37,
        user: "Kevin",
        game: "Slot Machine",
        betAmount: "0.1 BTC",
        payout: "-0.3 BTC",
      },
      {
        id: 38,
        user: "Lena",
        game: "Baccarat",
        betAmount: "0.5 ETH",
        payout: "-1.0 ETH",
      },
      {
        id: 39,
        user: "Mark",
        game: "Craps",
        betAmount: "0.05 BTC",
        payout: "-0.1 BTC",
      },
      {
        id: 40,
        user: "Nora",
        game: "Roulette",
        betAmount: "0.01 ETH",
        payout: "-0.03 ETH",
      },
    // Add more data here...
  ];
  