export const dummydata = [
  {
    id: 1,
    user: "Alice",
    game: "Slot Machine",
    betAmount: "0.005",
    coin: "btc",
    add: true,
    payout: "+0.015",
  },
  {
    id: 2,
    user: "Bob",
    game: "Roulette",
    betAmount: "0.01",
    coin: "eth",
    add: true,
    payout: "+0.03",
  },
  {
    id: 3,
    user: "Charlie",
    game: "Blackjack",
    betAmount: "0.02",
    coin: "btc",
    add: true,
    payout: "+0.04",
  },
  {
    id: 4,
    user: "David",
    game: "Slot Machine",
    betAmount: "0.5",
    coin: "btc",
    add: false,
    payout: "-1.0",
  },
  {
    id: 5,
    user: "Eve",
    game: "Roulette",
    betAmount: "0.9",
    coin: "eth",
    add: false,
    payout: "-1",
  },
  {
    id: 6,
    user: "Frank",
    game: "Slot Machine",
    betAmount: "10",
    coin: "btc",
    add: false,
    payout: "-20",
  },
  {
    id: 7,
    user: "Grace",
    game: "Fortune Wheel",
    betAmount: "50",
    coin: "btc",
    add: true,
    payout: "+0.9",
  },
  {
    id: 8,
    user: "Harry",
    game: "Roulette",
    betAmount: "1",
    coin: "eth",
    add: true,
    payout: "+2",
  },
  {
    id: 9,
    user: "Ivy",
    game: "Blackjack",
    betAmount: "0.1",
    coin: "btc",
    add: false,
    payout: "-0.2",
  },
  {
    id: 10,
    user: "Jack",
    game: "Fortune Wheel",
    betAmount: "1",
    coin: "eth",
    add: true,
    payout: "+2",
  },
  {
    id: 11,
    user: "Kate",
    game: "Fortune Wheel",
    betAmount: "5",
    coin: "btc",
    add: true,
    payout: "+10",
  },
  {
    id: 12,
    user: "Liam",
    game: "Roulette",
    betAmount: "0.01",
    coin: "eth",
    add: true,
    payout: "+0.02",
  },
  {
    id: 13,
    user: "Mia",
    game: "Blackjack",
    betAmount: "0.05",
    coin: "btc",
    add: true,
    payout: "+0.1",
  },
  {
    id: 14,
    user: "Noah",
    game: "Roulette",
    betAmount: "0.1",
    coin: "eth",
    add: true,
    payout: "+0.2",
  },
  {
    id: 15,
    user: "Olivia",
    game: "Blackjack",
    betAmount: "0.5",
    coin: "btc",
    add: false,
    payout: "-1.0",
  },
  {
    id: 16,
    user: "Peter",
    game: "Fortune Wheel",
    betAmount: "0.90",
    coin: "eth",
    add: false,
    payout: "-10",
  },
  {
    id: 17,
    user: "Quinn",
    game: "Fortune Wheel",
    betAmount: "5",
    coin: "btc",
    add: false,
    payout: "-10",
  },
  {
    id: 18,
    user: "Rachel",
    game: "Roulette",
    betAmount: "0.05",
    coin: "eth",
    add: false,
    payout: "-0.1",
  },
  {
    id: 19,
    user: "Sam",
    game: "Blackjack",
    betAmount: "10",
    coin: "btc",
    add: false,
    payout: "-20",
  },
  {
    id: 20,
    user: "Tom",
    game: "Slot Machine",
    betAmount: "0.005",
    coin: "eth",
    add: false,
    payout: "-0.015",
  },
  {
    id: 21,
    user: "Uma",
    game: "Roulette",
    betAmount: "0.01",
    coin: "btc",
    add: false,
    payout: "-0.03",
  },
  {
    id: 22,
    user: "Victor",
    game: "Slot Machine",
    betAmount: "0.5",
    coin: "eth",
    add: false,
    payout: "-1.0",
  },
  {
    id: 23,
    user: "Wendy",
    game: "Slot Machine",
    betAmount: "10",
    coin: "btc",
    add: false,
    payout: "-20",
  },
  {
    id: 24,
    user: "Xander",
    game: "Roulette",
    betAmount: "0.90",
    coin: "eth",
    add: false,
    payout: "-10",
  },
  {
    id: 25,
    user: "Yara",
    game: "Blackjack",
    betAmount: "0.1",
    coin: "btc",
    add: false,
    payout: "-0.2",
  },
  {
    id: 26,
    user: "Zoe",
    game: "Fortune Wheel",
    betAmount: "1",
    coin: "eth",
    add: true,
    payout: "+2",
  },
  {
    id: 27,
    user: "Adam",
    game: "Slot Machine",
    betAmount: "0.01",
    coin: "btc",
    add: true,
    payout: "+0.03",
  },
  {
    id: 28,
    user: "Becky",
    game: "Slot Machine",
    betAmount: "0.05",
    coin: "eth",
    add: true,
    payout: "+0.1",
  },
  {
    id: 29,
    user: "Carl",
    game: "Slot Machine",
    betAmount: "0.90",
    coin: "btc",
    add: true,
    payout: "+10",
  },
  {
    id: 30,
    user: "Diana",
    game: "Roulette",
    betAmount: "0.1",
    coin: "eth",
    add: true,
    payout: "+0.2",
  },
  {
    id: 31,
    user: "Eric",
    game: "Fortune Wheel",
    betAmount: "0.05",
    coin: "btc",
    add: false,
    payout: "-0.1",
  },
  {
    id: 32,
    user: "Fiona",
    game: "Slot Machine",
    betAmount: "0.001",
    coin: "eth",
    add: false,
    payout: "-0.003",
  },
  {
    id: 33,
    user: "George",
    game: "Roulette",
    betAmount: "0.5",
    coin: "btc",
    add: false,
    payout: "-1.0",
  },
  {
    id: 34,
    user: "Holly",
    game: "Blackjack",
    betAmount: "10",
    coin: "eth",
    add: false,
    payout: "-20",
  },
  {
    id: 35,
    user: "Ian",
    game: "Slot Machine",
    betAmount: "0.01",
    coin: "btc",
    add: false,
    payout: "-0.03",
  },
  {
    id: 36,
    user: "Julia",
    game: "Roulette",
    betAmount: "0.05",
    coin: "eth",
    add: false,
    payout: "-0.1",
  },
  {
    id: 37,
    user: "Kevin",
    game: "Fortune Wheel",
    betAmount: "0.1",
    coin: "btc",
    add: false,
    payout: "-0.3",
  },
  {
    id: 38,
    user: "Lena",
    game: "Slot Machine",
    betAmount: "0.5",
    coin: "eth",
    add: false,
    payout: "-1.0",
  },
  {
    id: 39,
    user: "Mark",
    game: "Fortune Wheel",
    betAmount: "0.05",
    coin: "btc",
    add: false,
    payout: "-0.1",
  },
  {
    id: 40,
    user: "Nora",
    game: "Roulette",
    betAmount: "0.01",
    coin: "eth",
    add: false,
    payout: "-0.03",
  },
  {
    id: 41,
    user: "Oscar",
    game: "Blackjack",
    betAmount: "0.1",
    coin: "btc",
    add: false,
    payout: "-0.2",
  },
  {
    id: 42,
    user: "Paula",
    game: "Slot Machine",
    betAmount: "0.05",
    coin: "eth",
    add: false,
    payout: "-0.1",
  },
  {
    id: 43,
    user: "Quincy",
    game: "Roulette",
    betAmount: "0.1",
    coin: "btc",
    add: false,
    payout: "-0.3",
  },
  // Add more data if needed...
];
